/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.Proveedores;


/**
 *
 * @author rodrigopeniche
 */
public class PanelBuscarProveedor extends javax.swing.JPanel {

    /**
     * Creates new form PanelBuscarProveedor
     */
    public PanelBuscarProveedor( ) {
        initComponents( );
        
        campoTextoNombre.setVisible( false );
        etiquetaNombre.setVisible( false );
        campoTextoTel.setVisible( false );
        etiquetaTel.setVisible( false );
        campoTextoDireccion.setVisible( false );
        etiquetaDireccion.setVisible( false );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaInstruccion = new javax.swing.JLabel();
        campoTextoClave = new javax.swing.JTextField();
        etiquetaNombre = new javax.swing.JLabel();
        campoTextoNombre = new javax.swing.JTextField();
        etiquetaTel = new javax.swing.JLabel();
        campoTextoTel = new javax.swing.JTextField();
        etiquetaDireccion = new javax.swing.JLabel();
        campoTextoDireccion = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        etiquetaInstruccion.setText("Ingrese la clave del proveedor:");

        etiquetaNombre.setText("Nombre:");

        etiquetaTel.setText("Tel:");

        etiquetaDireccion.setText("Direccion:");

        botonBuscar.setText("Buscar");

        botonCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etiquetaInstruccion)
                            .addComponent(campoTextoClave, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaNombre)
                                    .addComponent(etiquetaTel)
                                    .addComponent(etiquetaDireccion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoTextoNombre)
                                    .addComponent(campoTextoTel)
                                    .addComponent(campoTextoDireccion)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(botonBuscar)
                        .addGap(39, 39, 39)
                        .addComponent(botonCancelar)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(etiquetaInstruccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombre)
                    .addComponent(campoTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaTel)
                    .addComponent(campoTextoTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDireccion)
                    .addComponent(campoTextoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscar)
                    .addComponent(botonCancelar))
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextField campoTextoClave;
    private javax.swing.JTextField campoTextoDireccion;
    private javax.swing.JTextField campoTextoNombre;
    private javax.swing.JTextField campoTextoTel;
    private javax.swing.JLabel etiquetaDireccion;
    private javax.swing.JLabel etiquetaInstruccion;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaTel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the botonBuscar
     */
    public javax.swing.JButton getBotonBuscar() {
        return botonBuscar;
    }

    /**
     * @param botonBuscar the botonBuscar to set
     */
    public void setBotonBuscar(javax.swing.JButton botonBuscar) {
        this.botonBuscar = botonBuscar;
    }

    /**
     * @return the botonCancelar
     */
    public javax.swing.JButton getBotonCancelar() {
        return botonCancelar;
    }

    /**
     * @param botonCancelar the botonCancelar to set
     */
    public void setBotonCancelar(javax.swing.JButton botonCancelar) {
        this.botonCancelar = botonCancelar;
    }

    /**
     * @return the campoTextoClave
     */
    public javax.swing.JTextField getCampoTextoClave() {
        return campoTextoClave;
    }

    
    public void setCampoTextoClave(String clave) {
        campoTextoClave.setText(clave);
    }

    /**
     * @return the campoTextoDireccion
     */
    public javax.swing.JTextField getCampoTextoDireccion() {
        return campoTextoDireccion;
    }

    /**
     * @param direccion
    */
    public void setCampoTextoDireccion(String direccion) {
        campoTextoDireccion.setText(direccion);
    }

    /**
     * @return the campoTextoNombre
     */
    public javax.swing.JTextField getCampoTextoNombre() {
        return campoTextoNombre;
    }

   
    public void setCampoTextoNombre(String nombre) {
        campoTextoNombre.setText(nombre);
    }

    /**
     * @return the campoTextoTel
     */
    public javax.swing.JTextField getCampoTextoTel() {
        return campoTextoTel;
    }

    /**
     * @param telefono
     */
    public void setCampoTextoTel(String telefono) {
        campoTextoTel.setText(telefono);
    }

    /**
     * @return the etiquetaDireccion
     */
    public javax.swing.JLabel getEtiquetaDireccion() {
        return etiquetaDireccion;
    }

    /**
     * @param etiquetaDireccion the etiquetaDireccion to set
     */
    public void setEtiquetaDireccion(javax.swing.JLabel etiquetaDireccion) {
        this.etiquetaDireccion = etiquetaDireccion;
    }

    /**
     * @return the etiquetaInstruccion
     */
    public javax.swing.JLabel getEtiquetaInstruccion() {
        return etiquetaInstruccion;
    }

    /**
     * @param etiquetaInstruccion the etiquetaInstruccion to set
     */
    public void setEtiquetaInstruccion(javax.swing.JLabel etiquetaInstruccion) {
        this.etiquetaInstruccion = etiquetaInstruccion;
    }

    /**
     * @return the etiquetaNombre
     */
    public javax.swing.JLabel getEtiquetaNombre() {
        return etiquetaNombre;
    }

    /**
     * @param etiquetaNombre the etiquetaNombre to set
     */
    public void setEtiquetaNombre(javax.swing.JLabel etiquetaNombre) {
        this.etiquetaNombre = etiquetaNombre;
    }

    /**
     * @return the etiquetaTel
     */
    public javax.swing.JLabel getEtiquetaTel() {
        return etiquetaTel;
    }

    /**
     * @param etiquetaTel the etiquetaTel to set
     */
    public void setEtiquetaTel(javax.swing.JLabel etiquetaTel) {
        this.etiquetaTel = etiquetaTel;
    }
    
    public void mostrarCampoTextoNombre(){
        campoTextoNombre.setVisible(true);
    }
    
    public void mostrarCampoTextoTel(){
        campoTextoTel.setVisible(true);
    }
    
    public void mostrarCampoTextoDireccion(){
        campoTextoDireccion.setVisible(true);
    }
    
    public void mostrarEtiquetaNombre(){
        etiquetaNombre.setVisible(true);
    }
    
    public void mostrarEtiquetaTel(){
        etiquetaTel.setVisible(true);
    }
    
    public void mostrarEtiquetaDireccion(){
        etiquetaDireccion.setVisible(true);
    }
    
    
}
