/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.Proveedores;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rodrigopeniche
 */
public class PanelVerProveedores extends javax.swing.JPanel {
    
    private VentanaProveedores ventanaProveedores;
    private DefaultTableModel contenidoTablaProveedores;
    /**
     * Creates new form PanelVerProveedores
     * @param ventanaPrincipal
     */
    PanelVerProveedores( ) {
        initComponents( );
                
        contenidoTablaProveedores = new DefaultTableModel( );
        String camposTabla[] = new String[]{"Clave", "Nombre", "Teléfono", "Dirección"};
        contenidoTablaProveedores.setColumnIdentifiers( camposTabla );
        tablaProveedores.setModel( contenidoTablaProveedores );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaProveedores = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        botonBuscar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();

        etiquetaProveedores.setText("Proveedores:");

        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProveedores);

        botonBuscar.setText("Buscar proveedor");

        botonEliminar.setText("Eliminar proveedor");

        botonActualizar.setText("Actualizar proveedor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(botonBuscar)
                        .addGap(59, 59, 59)
                        .addComponent(botonEliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(etiquetaProveedores))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(botonActualizar)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(etiquetaProveedores)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscar)
                    .addComponent(botonEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonActualizar)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JLabel etiquetaProveedores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProveedores;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the ventanaProveedores
     */
    public VentanaProveedores getVentanaProveedores() {
        return ventanaProveedores;
    }

    /**
     * @param ventanaProveedores the ventanaProveedores to set
     */
    public void setVentanaProveedores(VentanaProveedores ventanaProveedores) {
        this.ventanaProveedores = ventanaProveedores;
    }

    /**
     * @return the contenidoTablaProveedores
     */
    public DefaultTableModel getContenidoTablaProveedores() {
        return contenidoTablaProveedores;
    }

    /**
     * @param contenidoTablaProveedores the contenidoTablaProveedores to set
     */
    public void setContenidoTablaProveedores(DefaultTableModel contenidoTablaProveedores) {
        this.contenidoTablaProveedores = contenidoTablaProveedores;
    }

    /**
     * @return the botonActualizar
     */
    public javax.swing.JButton getBotonActualizar() {
        return botonActualizar;
    }

    /**
     * @param botonActualizar the botonActualizar to set
     */
    public void setBotonActualizar(javax.swing.JButton botonActualizar) {
        this.botonActualizar = botonActualizar;
    }

    /**
     * @return the botonBuscar
     */
    public javax.swing.JButton getBotonBuscar() {
        return botonBuscar;
    }

    /**
     * @param botonBuscar the botonBuscar to set
     */
    public void setBotonBuscar(javax.swing.JButton botonBuscar) {
        this.botonBuscar = botonBuscar;
    }

    /**
     * @return the botonEliminar
     */
    public javax.swing.JButton getBotonEliminar() {
        return botonEliminar;
    }

    /**
     * @param botonEliminar the botonEliminar to set
     */
    public void setBotonEliminar(javax.swing.JButton botonEliminar) {
        this.botonEliminar = botonEliminar;
    }

    /**
     * @return the etiquetaProveedores
     */
    public javax.swing.JLabel getEtiquetaProveedores() {
        return etiquetaProveedores;
    }

    /**
     * @param etiquetaProveedores the etiquetaProveedores to set
     */
    public void setEtiquetaProveedores(javax.swing.JLabel etiquetaProveedores) {
        this.etiquetaProveedores = etiquetaProveedores;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the tablaProveedores
     */
    public javax.swing.JTable getTablaProveedores() {
        return tablaProveedores;
    }

    /**
     * @param tablaProveedores the tablaProveedores to set
     */
    public void setTablaProveedores(javax.swing.JTable tablaProveedores) {
        this.tablaProveedores = tablaProveedores;
    }
}
