/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.Inventario;


/**
 *
 * @author rodrigopeniche
 */
public class PanelBuscarArticulo extends javax.swing.JPanel {

    /**
     * Creates new form PanelVerInventario
     */
    public PanelBuscarArticulo( ) {
        initComponents( );
 
        campoTextoDescripcion.setVisible( false );
        campoTextoDescripcion.setEditable(false);
        etiquetaDescripcion.setVisible( false );
        campoTextoCantidad.setVisible( false );
        campoTextoCantidad.setEditable( false );
        etiquetaCantidad.setVisible( false );
        campoTextoPrecioCompra.setVisible( false );
        campoTextoPrecioCompra.setEditable( false );
        etiquetaPrecioVenta.setVisible( false );
        etiquetaPrecioCompra.setVisible(false);
        campoTextoPrecioVenta.setVisible( false );
        campoTextoPrecioVenta.setEditable( false );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaInstruccion = new javax.swing.JLabel();
        campoTextoClave = new javax.swing.JTextField();
        etiquetaDescripcion = new javax.swing.JLabel();
        campoTextoDescripcion = new javax.swing.JTextField();
        etiquetaCantidad = new javax.swing.JLabel();
        campoTextoCantidad = new javax.swing.JTextField();
        etiquetaPrecioCompra = new javax.swing.JLabel();
        campoTextoPrecioCompra = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        etiquetaPrecioVenta = new javax.swing.JLabel();
        campoTextoPrecioVenta = new javax.swing.JTextField();
        botonCancelar = new javax.swing.JButton();

        etiquetaInstruccion.setText("Ingrese la clave del artículo:");

        etiquetaDescripcion.setText("Descripción:");

        etiquetaCantidad.setText("Cantidad:");

        etiquetaPrecioCompra.setText("Precio compra:");

        botonBuscar.setText("Buscar");

        etiquetaPrecioVenta.setText("Precio venta:");

        botonCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaPrecioVenta)
                            .addComponent(campoTextoClave, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaInstruccion)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaDescripcion)
                                    .addComponent(etiquetaCantidad)
                                    .addComponent(etiquetaPrecioCompra))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoTextoPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoTextoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoTextoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoTextoPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(botonBuscar)
                        .addGap(57, 57, 57)
                        .addComponent(botonCancelar)))
                .addGap(73, 99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(etiquetaInstruccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoTextoClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDescripcion)
                    .addComponent(campoTextoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCantidad)
                    .addComponent(campoTextoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaPrecioCompra)
                    .addComponent(campoTextoPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaPrecioVenta)
                    .addComponent(campoTextoPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscar)
                    .addComponent(botonCancelar))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextField campoTextoCantidad;
    private javax.swing.JTextField campoTextoClave;
    private javax.swing.JTextField campoTextoDescripcion;
    private javax.swing.JTextField campoTextoPrecioCompra;
    private javax.swing.JTextField campoTextoPrecioVenta;
    private javax.swing.JLabel etiquetaCantidad;
    private javax.swing.JLabel etiquetaDescripcion;
    private javax.swing.JLabel etiquetaInstruccion;
    private javax.swing.JLabel etiquetaPrecioCompra;
    private javax.swing.JLabel etiquetaPrecioVenta;
    // End of variables declaration//GEN-END:variables

    /**
     * @param cantidad
     * @return the botonBuscar
     */
    
    public javax.swing.JButton getBotonBuscar() {
        return botonBuscar;
    }

    /**
     * @param botonBuscar the botonBuscar to set
     */
    public void setBotonBuscar(javax.swing.JButton botonBuscar) {
        this.botonBuscar = botonBuscar;
    }

    /**
     * @return the botonCancelar
     */
    public javax.swing.JButton getBotonCancelar() {
        return botonCancelar;
    }

    /**
     * @param botonCancelar the botonCancelar to set
     */
    public void setBotonCancelar(javax.swing.JButton botonCancelar) {
        this.botonCancelar = botonCancelar;
    }

    /**
     * @return the campoTextoCantidad
     */
    public javax.swing.JTextField getCampoTextoCantidad() {
        return campoTextoCantidad;
    }

    /**
     * @param cantidad
     * @param campoTextoCantidad the campoTextoCantidad to set
     */
    public void setCampoTextoCantidad(String cantidad) {
        campoTextoCantidad.setText(cantidad);
    }

    /**
     * @return the campoTextoClave
     */
    public javax.swing.JTextField getCampoTextoClave() {
        return campoTextoClave;
    }

    /**
     * @param campoTextoClave the campoTextoClave to set
     */
    /**
     * @return the campoTextoDescripcion
     */
    public javax.swing.JTextField getCampoTextoDescripcion() {
        return campoTextoDescripcion;
    }
    
    public void setCampoTextoDescripcion(String descripcion){
        campoTextoDescripcion.setText(descripcion);
    }

    /**
     * @param campoTextoDescripcion the campoTextoDescripcion to set
     */

    /**
     * @return the campoTextoPrecioCompra
     */
    public javax.swing.JTextField getCampoTextoPrecioCompra() {
        return campoTextoPrecioCompra;
    }
    
    public void setCampoTextoPrecioCompra(String precioCompra){
        campoTextoPrecioCompra.setText(precioCompra);
    }

    /**
     * @param campoTextoPrecioCompra the campoTextoPrecioCompra to set
     */

    /**
     * @return the campoTextoPrecioVenta
     */
    public javax.swing.JTextField getCampoTextoPrecioVenta() {
        return campoTextoPrecioVenta;
    }
    
    public void setCampoTextoPrecioVenta(String precioVenta){
        campoTextoPrecioVenta.setText(precioVenta);
    }

    /**
     * @param campoTextoPrecioVenta the campoTextoPrecioVenta to set
     */

    /**
     * @return the etiquetaCantidad
     */
    public javax.swing.JLabel getEtiquetaCantidad() {
        return etiquetaCantidad;
    }

    /**
     * @param etiquetaCantidad the etiquetaCantidad to set
     */
    public void setEtiquetaCantidad(javax.swing.JLabel etiquetaCantidad) {
        this.etiquetaCantidad = etiquetaCantidad;
    }

    /**
     * @return the etiquetaDescripcion
     */
    public javax.swing.JLabel getEtiquetaDescripcion() {
        return etiquetaDescripcion;
    }

    /**
     * @param etiquetaDescripcion the etiquetaDescripcion to set
     */
    public void setEtiquetaDescripcion(javax.swing.JLabel etiquetaDescripcion) {
        this.etiquetaDescripcion = etiquetaDescripcion;
    }

    /**
     * @return the etiquetaInstruccion
     */
    public javax.swing.JLabel getEtiquetaInstruccion() {
        return etiquetaInstruccion;
    }

    /**
     * @param etiquetaInstruccion the etiquetaInstruccion to set
     */
    public void setEtiquetaInstruccion(javax.swing.JLabel etiquetaInstruccion) {
        this.etiquetaInstruccion = etiquetaInstruccion;
    }

    /**
     * @return the etiquetaPrecioCompra
     */
    public javax.swing.JLabel getEtiquetaPrecioCompra() {
        return etiquetaPrecioCompra;
    }

    /**
     * @param etiquetaPrecioCompra the etiquetaPrecioCompra to set
     */
    public void setEtiquetaPrecioCompra(javax.swing.JLabel etiquetaPrecioCompra) {
        this.etiquetaPrecioCompra = etiquetaPrecioCompra;
    }

    /**
     * @return the etiquetaPrecioVenta
     */
    public javax.swing.JLabel getEtiquetaPrecioVenta() {
        return etiquetaPrecioVenta;
    }

    /**
     * @param etiquetaPrecioVenta the etiquetaPrecioVenta to set
     */
    public void setEtiquetaPrecioVenta(javax.swing.JLabel etiquetaPrecioVenta) {
        this.etiquetaPrecioVenta = etiquetaPrecioVenta;
    }
    
    public void mostrarCampoTextoCantidad(){
        campoTextoCantidad.setVisible(true);
    }
    
    public void mostrarCampoTextoDescripcion( ){
        campoTextoDescripcion.setVisible(true);
    }
    
    public void mostrarCampoTextoPrecioCompra(){
        campoTextoPrecioCompra.setVisible(true);
    }
    
    public void mostrarCampoTextoPrecioVenta(){
        campoTextoPrecioVenta.setVisible(true);
    }
    
    public void mostrarEtiquetaCantidad(){
        etiquetaCantidad.setVisible(true);
    }
    
    public void mostrarEtiquetaDescripcion(){
        etiquetaDescripcion.setVisible(true);
    }
    
    public void mostrarEtiquetaPrecioCompra(){
        etiquetaPrecioCompra.setVisible(true);
    }
    
    public void mostrarEtiquetaPrecioVenta(){
        etiquetaPrecioVenta.setVisible(true);
    }
    
    
}