/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.Empleados;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author rodrigopeniche
 */
public class PanelBuscarEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form PanelBuscarCliente
     */
    public PanelBuscarEmpleado() {
        initComponents();
        
        campoTextoNombre.setVisible( false );
        etiquetaNombre.setVisible( false );
        campoTextoTel.setVisible( false );
        etiquetaTel.setVisible( false );
        campoTextoDireccion.setVisible( false );
        etiquetaDireccion.setVisible( false );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoTextoClave = new javax.swing.JTextField();
        etiquetaNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        etiquetaDireccion = new javax.swing.JLabel();
        campoTextoNombre = new javax.swing.JTextField();
        campoTextoTel = new javax.swing.JTextField();
        campoTextoDireccion = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        etiquetaTel = new javax.swing.JLabel();

        jLabel1.setText("Ingrese la clave del empleado");

        etiquetaNombre.setText("Nombre:");

        etiquetaDireccion.setText("Dirección:");

        botonBuscar.setText("Buscar");

        botonCancelar.setText("Cancelar");

        etiquetaTel.setText("Tel:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoTextoClave, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaNombre)
                                    .addComponent(etiquetaDireccion)
                                    .addComponent(jLabel3)
                                    .addComponent(etiquetaTel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoTextoTel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoTextoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(botonBuscar)
                        .addGap(43, 43, 43)
                        .addComponent(botonCancelar)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombre)
                    .addComponent(campoTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoTextoTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etiquetaTel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDireccion)
                    .addComponent(campoTextoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscar)
                    .addComponent(botonCancelar))
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextField campoTextoClave;
    private javax.swing.JTextField campoTextoDireccion;
    private javax.swing.JTextField campoTextoNombre;
    private javax.swing.JTextField campoTextoTel;
    private javax.swing.JLabel etiquetaDireccion;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    public JButton getBotonBuscar() {
        return botonBuscar;
    }

    public JButton getBotonCancelar() {
        return botonCancelar;
    }

    public JTextField getCampoTextoClave() {
        return campoTextoClave;
    }

    public JTextField getCampoTextoDireccion() {
        return campoTextoDireccion;
    }

    public JTextField getCampoTextoNombre() {
        return campoTextoNombre;
    }

    public JTextField getCampoTextoTel() {
        return campoTextoTel;
    }

    public JLabel getEtiquetaDireccion() {
        return etiquetaDireccion;
    }

    public JLabel getEtiquetaNombre() {
        return etiquetaNombre;
    }

    public JLabel getEtiquetaTel() {
        return etiquetaTel;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setBotonBuscar(JButton botonBuscar) {
        this.botonBuscar = botonBuscar;
    }

    public void setBotonCancelar(JButton botonCancelar) {
        this.botonCancelar = botonCancelar;
    }

    public void setCampoTextoClave(JTextField campoTextoClave) {
        this.campoTextoClave = campoTextoClave;
    }

    public void setCampoTextoDireccion(String direccion) {
        campoTextoDireccion.setText(direccion);
    }

    public void setCampoTextoNombre(String nombre) {
        campoTextoNombre.setText(nombre);
    }

    public void setCampoTextoTel(String tel) {
        campoTextoTel.setText(tel);
    }

    public void setEtiquetaDireccion(JLabel etiquetaDireccion) {
        this.etiquetaDireccion = etiquetaDireccion;
    }

    public void setEtiquetaNombre(JLabel etiquetaNombre) {
        this.etiquetaNombre = etiquetaNombre;
    }

    public void setEtiquetaTel(JLabel etiquetaTel) {
        this.etiquetaTel = etiquetaTel;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public void mostrarCampoTextoNombre() {
        campoTextoNombre.setVisible(true);
    }

    public void mostrarCampoTextoTel() {
        campoTextoTel.setVisible(true);
    }

    public void mostrarCampoTextoDireccion() {
        campoTextoDireccion.setVisible(true);
    }

    public void mostrarEtiquetaNombre() {
        etiquetaNombre.setVisible(true);
    }

    public void mostrarEtiquetaTel() {
        etiquetaTel.setVisible(true);
    }

    public void mostrarEtiquetaDireccion() {
        etiquetaDireccion.setVisible(true);
    }

    
}
