/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.Inventario;

/**
 *
 * @author rodrigopeniche
 */
public class PanelAgregarArticulo extends javax.swing.JPanel {
    
    /**
     * Creates new form PanelAgregarArticulo
     */
    public PanelAgregarArticulo( ) {
        initComponents( );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaClave = new javax.swing.JLabel();
        etiquetaDescripcion = new javax.swing.JLabel();
        etiquetaCantidad = new javax.swing.JLabel();
        etiquetaPrecioCompra = new javax.swing.JLabel();
        campoTextoClave = new javax.swing.JTextField();
        campoTextoDescripcion = new javax.swing.JTextField();
        campoTextoCantidad = new javax.swing.JTextField();
        campoTextoPrecioCompra = new javax.swing.JTextField();
        botonAgregarArticulo = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        etiquetaClaveProveedor = new javax.swing.JLabel();
        campoTextoClaveProveedor = new javax.swing.JTextField();
        etiquetaAgregarArticulo = new javax.swing.JLabel();
        etiquetaPrecioVenta = new javax.swing.JLabel();
        campoTextoPrecioVenta = new javax.swing.JTextField();

        etiquetaClave.setText("Clave:");

        etiquetaDescripcion.setText("Descripción:");

        etiquetaCantidad.setText("Cantidad:");

        etiquetaPrecioCompra.setText("Precio compra:");

        botonAgregarArticulo.setText("Agregar");

        botonCancelar.setText("Cancelar");

        etiquetaClaveProveedor.setText("Clave Proveedor:");

        etiquetaAgregarArticulo.setText("Agregar artículo");

        etiquetaPrecioVenta.setText("Precio venta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAgregarArticulo)
                        .addGap(58, 58, 58)
                        .addComponent(botonCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaDescripcion)
                                    .addComponent(etiquetaCantidad)
                                    .addComponent(etiquetaPrecioCompra)
                                    .addComponent(etiquetaPrecioVenta))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoTextoDescripcion)
                                    .addComponent(campoTextoCantidad)
                                    .addComponent(campoTextoPrecioCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(campoTextoPrecioVenta)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaAgregarArticulo)
                                    .addComponent(etiquetaClaveProveedor))
                                .addGap(18, 18, 18)
                                .addComponent(campoTextoClaveProveedor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiquetaClave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addComponent(campoTextoClave, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(etiquetaAgregarArticulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaClave)
                    .addComponent(campoTextoClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaClaveProveedor)
                    .addComponent(campoTextoClaveProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDescripcion)
                    .addComponent(campoTextoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCantidad)
                    .addComponent(campoTextoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaPrecioCompra)
                    .addComponent(campoTextoPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaPrecioVenta)
                    .addComponent(campoTextoPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregarArticulo)
                    .addComponent(botonCancelar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarArticulo;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextField campoTextoCantidad;
    private javax.swing.JTextField campoTextoClave;
    private javax.swing.JTextField campoTextoClaveProveedor;
    private javax.swing.JTextField campoTextoDescripcion;
    private javax.swing.JTextField campoTextoPrecioCompra;
    private javax.swing.JTextField campoTextoPrecioVenta;
    private javax.swing.JLabel etiquetaAgregarArticulo;
    private javax.swing.JLabel etiquetaCantidad;
    private javax.swing.JLabel etiquetaClave;
    private javax.swing.JLabel etiquetaClaveProveedor;
    private javax.swing.JLabel etiquetaDescripcion;
    private javax.swing.JLabel etiquetaPrecioCompra;
    private javax.swing.JLabel etiquetaPrecioVenta;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the botonAgregarArticulo
     */
    public javax.swing.JButton getBotonAgregarArticulo() {
        return botonAgregarArticulo;
    }

    /**
     * @param botonAgregarArticulo the botonAgregarArticulo to set
     */
    public void setBotonAgregarArticulo(javax.swing.JButton botonAgregarArticulo) {
        this.botonAgregarArticulo = botonAgregarArticulo;
    }

    /**
     * @return the botonCancelar
     */
    public javax.swing.JButton getBotonCancelar() {
        return botonCancelar;
    }

    /**
     * @param botonCancelar the botonCancelar to set
     */
    public void setBotonCancelar(javax.swing.JButton botonCancelar) {
        this.botonCancelar = botonCancelar;
    }

    /**
     * @return the campoTextoCantidad
     */
    public javax.swing.JTextField getCampoTextoCantidad() {
        return campoTextoCantidad;
    }

    /**
     * @param campoTextoCantidad the campoTextoCantidad to set
     */
    public void setCampoTextoCantidad(javax.swing.JTextField campoTextoCantidad) {
        this.campoTextoCantidad = campoTextoCantidad;
    }

    /**
     * @return the campoTextoClave
     */
    public javax.swing.JTextField getCampoTextoClave() {
        return campoTextoClave;
    }

    /**
     * @param campoTextoClave the campoTextoClave to set
     */
    public void setCampoTextoClave(javax.swing.JTextField campoTextoClave) {
        this.campoTextoClave = campoTextoClave;
    }

    /**
     * @return the campoTextoClaveProveedor
     */
    public javax.swing.JTextField getCampoTextoClaveProveedor() {
        return campoTextoClaveProveedor;
    }

    /**
     * @param campoTextoClaveProveedor the campoTextoClaveProveedor to set
     */
    public void setCampoTextoClaveProveedor(javax.swing.JTextField campoTextoClaveProveedor) {
        this.campoTextoClaveProveedor = campoTextoClaveProveedor;
    }

    /**
     * @return the campoTextoDescripcion
     */
    public javax.swing.JTextField getCampoTextoDescripcion() {
        return campoTextoDescripcion;
    }

    /**
     * @param campoTextoDescripcion the campoTextoDescripcion to set
     */
    public void setCampoTextoDescripcion(javax.swing.JTextField campoTextoDescripcion) {
        this.campoTextoDescripcion = campoTextoDescripcion;
    }

    /**
     * @return the campoTextoPrecioCompra
     */
    public javax.swing.JTextField getCampoTextoPrecioCompra() {
        return campoTextoPrecioCompra;
    }

    /**
     * @param campoTextoPrecioCompra the campoTextoPrecioCompra to set
     */
    public void setCampoTextoPrecioCompra(javax.swing.JTextField campoTextoPrecioCompra) {
        this.campoTextoPrecioCompra = campoTextoPrecioCompra;
    }

    /**
     * @return the campoTextoPrecioVenta
     */
    public javax.swing.JTextField getCampoTextoPrecioVenta() {
        return campoTextoPrecioVenta;
    }

    /**
     * @param campoTextoPrecioVenta the campoTextoPrecioVenta to set
     */
    public void setCampoTextoPrecioVenta(javax.swing.JTextField campoTextoPrecioVenta) {
        this.campoTextoPrecioVenta = campoTextoPrecioVenta;
    }

    /**
     * @return the etiquetaAgregarArticulo
     */
    public javax.swing.JLabel getEtiquetaAgregarArticulo() {
        return etiquetaAgregarArticulo;
    }

    /**
     * @param etiquetaAgregarArticulo the etiquetaAgregarArticulo to set
     */
    public void setEtiquetaAgregarArticulo(javax.swing.JLabel etiquetaAgregarArticulo) {
        this.etiquetaAgregarArticulo = etiquetaAgregarArticulo;
    }

    /**
     * @return the etiquetaCantidad
     */
    public javax.swing.JLabel getEtiquetaCantidad() {
        return etiquetaCantidad;
    }

    /**
     * @param etiquetaCantidad the etiquetaCantidad to set
     */
    public void setEtiquetaCantidad(javax.swing.JLabel etiquetaCantidad) {
        this.etiquetaCantidad = etiquetaCantidad;
    }

    /**
     * @return the etiquetaClave
     */
    public javax.swing.JLabel getEtiquetaClave() {
        return etiquetaClave;
    }

    /**
     * @param etiquetaClave the etiquetaClave to set
     */
    public void setEtiquetaClave(javax.swing.JLabel etiquetaClave) {
        this.etiquetaClave = etiquetaClave;
    }

    /**
     * @return the etiquetaClaveProveedor
     */
    public javax.swing.JLabel getEtiquetaClaveProveedor() {
        return etiquetaClaveProveedor;
    }

    /**
     * @param etiquetaClaveProveedor the etiquetaClaveProveedor to set
     */
    public void setEtiquetaClaveProveedor(javax.swing.JLabel etiquetaClaveProveedor) {
        this.etiquetaClaveProveedor = etiquetaClaveProveedor;
    }

    /**
     * @return the etiquetaDescripcion
     */
    public javax.swing.JLabel getEtiquetaDescripcion() {
        return etiquetaDescripcion;
    }

    /**
     * @param etiquetaDescripcion the etiquetaDescripcion to set
     */
    public void setEtiquetaDescripcion(javax.swing.JLabel etiquetaDescripcion) {
        this.etiquetaDescripcion = etiquetaDescripcion;
    }

    /**
     * @return the etiquetaPrecioCompra
     */
    public javax.swing.JLabel getEtiquetaPrecioCompra() {
        return etiquetaPrecioCompra;
    }

    /**
     * @param etiquetaPrecioCompra the etiquetaPrecioCompra to set
     */
    public void setEtiquetaPrecioCompra(javax.swing.JLabel etiquetaPrecioCompra) {
        this.etiquetaPrecioCompra = etiquetaPrecioCompra;
    }

    /**
     * @return the etiquetaPrecioVenta
     */
    public javax.swing.JLabel getEtiquetaPrecioVenta() {
        return etiquetaPrecioVenta;
    }

    /**
     * @param etiquetaPrecioVenta the etiquetaPrecioVenta to set
     */
    public void setEtiquetaPrecioVenta(javax.swing.JLabel etiquetaPrecioVenta) {
        this.etiquetaPrecioVenta = etiquetaPrecioVenta;
    }
}
